id: 998f0654-4a9b-4a53-8fb6-f25b88d587d6
version: 28
name: Confluence Integration Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7d3c670d-47e0-4580-8c17-8a346a56e227
    type: start
    task:
      id: 7d3c670d-47e0-4580-8c17-8a346a56e227
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": -160
        }
      }
    note: false
  "1":
    id: "1"
    taskid: d144353a-90c8-4262-82bc-c6893aa47352
    type: regular
    task:
      id: d144353a-90c8-4262-82bc-c6893aa47352
      version: -1
      name: Create new Confluence Space to add Page content
      script: Atlassian Confluence Server|||confluence-create-space
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      description:
        simple: Test Space from Playbook
      key:
        simple: PBSPC
      name:
        simple: Test Space from Playbook  - ${incident.id}:${incident.created}
      type:
        simple: global
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
    note: false
  "2":
    id: "2"
    taskid: c8cac5a9-c9b4-4de5-8274-82a6aa75a96f
    type: title
    task:
      id: c8cac5a9-c9b4-4de5-8274-82a6aa75a96f
      version: -1
      name: Create New Space
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "3":
    id: "3"
    taskid: f04b780d-77b4-4cc4-89e5-832f45ab6d2b
    type: regular
    task:
      id: f04b780d-77b4-4cc4-89e5-832f45ab6d2b
      version: -1
      name: Create new Confluence Page in PBSPC (Space created in previous step)
      script: Atlassian Confluence Server|||confluence-create-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      body:
        simple: <h1>Incident ID ${incident.id}</h1><p>Hello from Demisto Playbook,
          Incident ID ${incident.id} created on ${incident.created}.</p>
      space:
        simple: ${Confluence.Space.Create.key}
      title:
        simple: Test Page created from Playbook automation - ${incident.id}:${incident.created}
      type:
        simple: page
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1155
        }
      }
    note: false
  "4":
    id: "4"
    taskid: e4890acf-a36d-4fde-8b32-d3ab2263b9fc
    type: title
    task:
      id: e4890acf-a36d-4fde-8b32-d3ab2263b9fc
      version: -1
      name: Create New Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1010
        }
      }
    note: false
  "5":
    id: "5"
    taskid: c7738f26-5af0-4229-89db-d650a7fee217
    type: regular
    task:
      id: c7738f26-5af0-4229-89db-d650a7fee217
      version: -1
      name: Get a full List of Spaces from Confluence
      script: Atlassian Confluence Server|||confluence-list-spaces
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 660
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 4f9d0f68-2d41-459a-827b-c4df369c759c
    type: title
    task:
      id: 4f9d0f68-2d41-459a-827b-c4df369c759c
      version: -1
      name: List Spaces
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
    note: false
  "7":
    id: "7"
    taskid: e68da46c-861c-4352-8dc8-de89c3c5d5f7
    type: condition
    task:
      id: e68da46c-861c-4352-8dc8-de89c3c5d5f7
      version: -1
      name: Check to see if any Spaces were returned and that the newly created Space
        exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Confluence.Space.List.results
            iscontext: true
      - - operator: containsGeneral
          left:
            value:
              simple: Confluence.Space.List.results.key
            iscontext: true
          right:
            value:
              simple: Confluence.Space.Create.key
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 835
        }
      }
    note: false
  "8":
    id: "8"
    taskid: fea6a891-abd7-4b03-8790-455262e3c258
    type: regular
    task:
      id: fea6a891-abd7-4b03-8790-455262e3c258
      version: -1
      name: Manually check Space list and look for key PBSPC
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      value:
        simple: Something went wrong
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -210,
          "y": 2220
        }
      }
    note: false
  "9":
    id: "9"
    taskid: cb5d1a07-c04a-4db1-89f5-12c2848de2f3
    type: condition
    task:
      id: cb5d1a07-c04a-4db1-89f5-12c2848de2f3
      version: -1
      name: Check to see if any Pages were returned and that the newly created Page
        exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Confluence.Content.Search.results
            iscontext: true
      - - operator: containsString
          left:
            value:
              simple: Confluence.Content.Create.title
            iscontext: true
          right:
            value:
              simple: Confluence.Content.Create.title
            iscontext: true
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1825
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 86e02d6c-5e17-4393-8dbf-807da65723b5
    type: title
    task:
      id: 86e02d6c-5e17-4393-8dbf-807da65723b5
      version: -1
      name: Update Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2000
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 53996a72-bff7-4d1f-8323-8fe7c587513a
    type: regular
    task:
      id: 53996a72-bff7-4d1f-8323-8fe7c587513a
      version: -1
      name: Update Page body with success message
      script: Atlassian Confluence Server|||confluence-update-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      body:
        simple: ${Confluence.Content.Create.body.storage.value}<br/><br/><p>This is
          a successful Page update!</p>
      currentversion:
        simple: ${Confluence.Content.Create.version.number}
      pageid:
        simple: ${Confluence.Content.Create.id}
      space: {}
      title:
        simple: ${Confluence.Content.Create.title}
      type:
        simple: page
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2145
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 8cdb7894-0396-4964-8999-318b88ec4eb0
    type: regular
    task:
      id: 8cdb7894-0396-4964-8999-318b88ec4eb0
      version: -1
      name: Manually check Page list and look for newly created Page
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      value:
        simple: Something went wrong with new Page creation.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 300,
          "y": 2225
        }
      }
    note: false
  "13":
    id: "13"
    taskid: aa9fefdb-78c8-4ecd-8774-099157ea3d3f
    type: title
    task:
      id: aa9fefdb-78c8-4ecd-8774-099157ea3d3f
      version: -1
      name: Search for New Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1330
        }
      }
    note: false
  "14":
    id: "14"
    taskid: aa4c481c-0e10-4922-888e-211dbb03d262
    type: regular
    task:
      id: aa4c481c-0e10-4922-888e-211dbb03d262
      version: -1
      name: Search for newly created Page using CQL
      script: Atlassian Confluence Server|||confluence-search-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      cql:
        simple: id = ${Confluence.Content.Create.id}
      cqlcontext: {}
      expand: {}
      limit: {}
      start: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1650
        }
      }
    note: false
  "16":
    id: "16"
    taskid: b66b9215-699a-4ed0-8383-73d1e5814bfa
    type: regular
    task:
      id: b66b9215-699a-4ed0-8383-73d1e5814bfa
      version: -1
      name: Close as failure
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: CustomCloseReason
      value:
        simple: SpaceCreationFailure
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 3485
        }
      }
    note: false
  "17":
    id: "17"
    taskid: fd8ccaa1-d210-44d9-83fb-0e98ee349cc6
    type: regular
    task:
      id: fd8ccaa1-d210-44d9-83fb-0e98ee349cc6
      version: -1
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason:
        simple: ${CustomCloseReason}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 3660
        }
      }
    note: false
  "18":
    id: "18"
    taskid: c469f25f-bc04-4b6e-8be9-4f8fe0385699
    type: title
    task:
      id: c469f25f-bc04-4b6e-8be9-4f8fe0385699
      version: -1
      name: Capture Page Image
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2320
        }
      }
    note: false
  "19":
    id: "19"
    taskid: e88bdbe4-3728-466c-8793-83a975e67198
    type: regular
    task:
      id: e88bdbe4-3728-466c-8793-83a975e67198
      version: -1
      name: Use raterize to capture page image
      script: Rasterize|||rasterize
      type: regular
      iscommand: true
      brand: Rasterize
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      height: {}
      type: {}
      url:
        complex:
          root: Confluence
          accessor: Content.Create._links
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: base
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: Confluence.Content.Create._links.tinyui
                iscontext: true
      width: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2465
        }
      }
    note: false
  "20":
    id: "20"
    taskid: f6daecf2-872f-41e5-83cf-e8658bff86e7
    type: regular
    task:
      id: f6daecf2-872f-41e5-83cf-e8658bff86e7
      version: -1
      name: Review the page image in war room before deleting ...
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2640
        }
      }
    note: false
  "21":
    id: "21"
    taskid: 3eb3c440-28ef-43bf-84b8-e68a678f53bc
    type: regular
    task:
      id: 3eb3c440-28ef-43bf-84b8-e68a678f53bc
      version: -1
      name: Close as success
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: CustomCloseReason
      value:
        simple: PageCreationSuccess
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 920,
          "y": 3485
        }
      }
    note: false
  "22":
    id: "22"
    taskid: ce9fa83c-f330-4106-84e6-a0e0cbb51a29
    type: title
    task:
      id: ce9fa83c-f330-4106-84e6-a0e0cbb51a29
      version: -1
      name: Delete Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2815
        }
      }
    note: false
  "23":
    id: "23"
    taskid: 076b449e-8135-4640-8391-1db1b4b6556e
    type: regular
    task:
      id: 076b449e-8135-4640-8391-1db1b4b6556e
      version: -1
      name: Get newly created page object from Confluence
      script: Atlassian Confluence Server|||confluence-get-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      key:
        simple: ${Confluence.Space.Create.key}
      title:
        simple: ${Confluence.Content.Create.title}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2960
        }
      }
    note: false
  "24":
    id: "24"
    taskid: e45de982-8748-42dd-8ab1-e10d82f5d229
    type: regular
    task:
      id: e45de982-8748-42dd-8ab1-e10d82f5d229
      version: -1
      name: Delete page
      script: Atlassian Confluence Server|||confluence-delete-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      id:
        simple: ${Confluence.Content.Get.results.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3135
        }
      }
    note: false
  "25":
    id: "25"
    taskid: bd047bdf-e8fb-4f8c-8dcd-2f94cd614a66
    type: condition
    task:
      id: bd047bdf-e8fb-4f8c-8dcd-2f94cd614a66
      version: -1
      name: Page Deletion successful?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "21"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsString
          left:
            value:
              simple: Confluence.Content.Delete.results
            iscontext: true
          right:
            value:
              simple: success
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3310
        }
      }
    note: false
  "26":
    id: "26"
    taskid: f19e8a02-bb98-428c-84f2-981232c31304
    type: regular
    task:
      id: f19e8a02-bb98-428c-84f2-981232c31304
      version: -1
      name: Sleep for a few seconds...
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1475
        }
      }
    note: false
  "27":
    id: "27"
    taskid: de04a461-92d9-4c89-89a6-a0822c10b3f2
    type: regular
    task:
      id: de04a461-92d9-4c89-89a6-a0822c10b3f2
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 0
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {
      "7_8_#default#": 0.42
    },
    "paper": {
      "dimensions": {
        "height": 3915,
        "width": 1510,
        "x": -210,
        "y": -160
      }
    }
  }
inputs: []
outputs: []
